name: portfolio

packages:
  - app/*
  - design_system/*
  - core/*

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: |
      Run all static analysis checks
      - Analyze the project for Dart analysis issues.
      - Requires `pub global activate tuneup`.

  get:
    run: |
      melos exec -c 5 -- \
        flutter pub get
    description: |
      Run `flutter pub get` in all packages.

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: dart pub global run flutter_plugin_tools format
    description: |
      Build a specific example app for Android.
       - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
       - Requires `clang-format` (can be installed via Brew on macOS).

  run:all:
    run: |
      melos exec -c 5 -- \
        flutter run -d all
    description: |
      Run project in all devices available

  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast --flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all Flutter tests in this project.

  gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh"
